module.name=murex-trade

jvm.opts=-server -Xms512m -Xmx512m -XX:MaxMetaspaceSize=196m
h2.opts=-server -Xms128m -Xmx128m -XX:MaxMetaspaceSize=32m

# Web Bindings
server.port=8080
public.service.address=murex-trade.ikasan.cloud.org
public.service.port=8080
server.servlet.context-path=/murex-trade

# health probs and remote management (optional)
management.endpoints.enabled-by-default=false
management.endpoint.info.enabled=true
management.endpoint.health.enabled=true
management.endpoint.logfile.enabled=true
management.endpoints.web.exposure.include=info,health,logfile
management.endpoint.shutdown.enabled=true

management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.health.jms.enabled=false

# Destination Names
# murex trade consumer flow
queue.com.caixa.bank.murex.out=dynamicQueues/fake.murex.queue
queue.com.caxia.bank.trade.out.bdm=dynamicTopics/bdm.post.trade

# murex trade producer flow
queue.com.caixa.bank.murex.in=dynamicQueues/bdm.trade
queue.com.caxia.bank.trade.in.bdm=dynamicQueues/fake.murex.queue

ikasan.exceptions.retry-configs.[0].className=org.ikasan.spec.component.endpoint.EndpointException
ikasan.exceptions.retry-configs.[0].delayInMillis=5000
ikasan.exceptions.retry-configs.[0].maxRetries=-1

ikasan.exceptions.excludedClasses[0]=org.ikasan.spec.component.transformation.TransformationException
